all:
	gcc -std=c11 -O3 -Wall -Wextra MTF.c ../../library/mtf/mtf.c -o ../../bin/MTF
	gcc -std=c11 -O3 -Wall -Wextra ReverseMTF.c ../../library/mtf/umtf.c -o ../../bin/ReverseMTF
clean:
	rm ../../bin/MTF ../../bin/ReverseMTF
