all:
	gcc -std=c11 -O3 -Wall -Wextra MTF.c ../../library/mtf/mtf.c -o ../../Bin/MTF
	gcc -std=c11 -O3 -Wall -Wextra ReverseMTF.c ../../library/mtf/umtf.c -o ../../Bin/ReverseMTF
clean:
	rm ../../Bin/MTF ../../Bin/ReverseMTF
