all:
	gcc -std=c11 -O3 -Wall -Wextra BWT.c ../../library/bwt/bwt.c -o ../../bin/BWT
	gcc -std=c11 -O3 -Wall -Wextra ReverseBWT.c ../../library/bwt/ubwt.c -o ../../bin/ReverseBWT
clean:
	rm ../../bin/BWT ../../bin/ReverseBWT
