all:
	gcc -std=c11 -O3 -Wall -Wextra BWT.c ../../library/bwt/bwt.c -o ../../Bin/BWT
	gcc -std=c11 -O3 -Wall -Wextra ReverseBWT.c ../../library/bwt/ubwt.c -o ../../Bin/ReverseBWT
clean:
	rm ../../Bin/BWT ../../Bin/ReverseBWT
